In [3]:
import pandas as pd
import numpy as np

In [48]:
cliente = pd.read_csv('cliente.csv')

In [49]:
cliente

,cod_concesion,cod_tipo_sujeto,COD_SUMINISTRO,SECTOR,COD_TIPO_SUMINISTRO,COD_CONTADOR_ACT
0,VR,PER,1000002,2,CONT,Q18EA019889G
1,VR,PER,1000003,0,CONT,J14LA719590L
2,VR,PER,1000004,3.2,CONT,991150195
3,VR,SOC,981003,3.2,SIN_CONT,NaN
4,VR,PER,1000005,NaN,CONT,1107103
...,...,...,...,...,...,...
7048,VR,PER,999994,0,CONT,Q19GA023797T
7049,VR,PER,999995,2.2,SIN_CONT,NaN
7050,VR,PER,999996,3.1,CONT,Q18GA043158V
7051,VR,PER,999997,3.2,CONT,Q19GA023965R
7052,VR,PER,999998,3.2,CONT,Q18GA037964C

In [4]:
df = pd.read_csv('caudales_filtered.csv')

In [5]:
df

,Canonical,RowKey,INF_Label,INF_Value,STA_Label,Sector_Neta
0,TOTALIZADOR,2021-08-01T00:15:00.000Z,LS Valladolid,851056.437500,12000 Valladolid,22120000
1,TOTALIZADOR,2021-08-01T00:30:00.000Z,LS Valladolid,851065.437500,12000 Valladolid,22120000
2,TOTALIZADOR,2021-08-01T00:45:00.000Z,LS Valladolid,851073.937500,12000 Valladolid,22120000
3,TOTALIZADOR,2021-08-01T01:00:00.000Z,LS Valladolid,851082.500000,12000 Valladolid,22120000
4,TOTALIZADOR,2021-08-01T01:15:00.000Z,LS Valladolid,851090.812500,12000 Valladolid,22120000
...,...,...,...,...,...,...
876322,CAUDAL,2022-07-17T06:45:00.000Z,LS-V Sureste,25.119999,12200 Sur Este,22122000
876323,CAUDAL,2022-07-17T07:00:00.000Z,LS-V Sureste,27.079999,12200 Sur Este,22122000
876324,PRESION_SALIDA_SECTOR,2022-07-17T06:45:00.000Z,LS-V Sureste,3.727626,12200 Sur Este,22122000
876325,PRESION_SALIDA_SECTOR,2022-07-17T07:00:00.000Z,LS-V Sureste,3.943999,12200 Sur Este,22122000
876326,VOLUMEN_DIARIO,2022-07-17T07:00:00.000Z,LS-V Sureste,706.609984,12200 Sur Este,22122000

In [7]:
#convert rowkey to datetime
df['RowKey'] = pd.to_datetime(df['RowKey'])

In [8]:
df

,Canonical,RowKey,INF_Label,INF_Value,STA_Label,Sector_Neta
0,TOTALIZADOR,2021-08-01 00:15:00+00:00,LS Valladolid,851056.437500,12000 Valladolid,22120000
1,TOTALIZADOR,2021-08-01 00:30:00+00:00,LS Valladolid,851065.437500,12000 Valladolid,22120000
2,TOTALIZADOR,2021-08-01 00:45:00+00:00,LS Valladolid,851073.937500,12000 Valladolid,22120000
3,TOTALIZADOR,2021-08-01 01:00:00+00:00,LS Valladolid,851082.500000,12000 Valladolid,22120000
4,TOTALIZADOR,2021-08-01 01:15:00+00:00,LS Valladolid,851090.812500,12000 Valladolid,22120000
...,...,...,...,...,...,...
876322,CAUDAL,2022-07-17 06:45:00+00:00,LS-V Sureste,25.119999,12200 Sur Este,22122000
876323,CAUDAL,2022-07-17 07:00:00+00:00,LS-V Sureste,27.079999,12200 Sur Este,22122000
876324,PRESION_SALIDA_SECTOR,2022-07-17 06:45:00+00:00,LS-V Sureste,3.727626,12200 Sur Este,22122000
876325,PRESION_SALIDA_SECTOR,2022-07-17 07:00:00+00:00,LS-V Sureste,3.943999,12200 Sur Este,22122000
876326,VOLUMEN_DIARIO,2022-07-17 07:00:00+00:00,LS-V Sureste,706.609984,12200 Sur Este,22122000

In [15]:
df["Sector_Neta"].unique()

array([22120000, 22121000, 22130000, 22110000, 22131000, 22132100,
       22122000, 22122100], dtype=int64)

In [20]:
unique_sector_neta = [22120000, 22121000, 22130000, 22110000, 22131000, 22132100,22122000, 22122100]

In [18]:
df['Canonical'].unique()

array(['TOTALIZADOR', 'PRESION_ENTRADA_SECTOR', 'VOLUMEN_DIARIO',
       'CAUDAL', 'PRESION_SALIDA_SECTOR', 'VOLUMEN'], dtype=object)

In [21]:
unique_canonical = ['TOTALIZADOR', 'PRESION_ENTRADA_SECTOR', 'VOLUMEN_DIARIO', 'CAUDAL', 'PRESION_SALIDA_SECTOR', 'VOLUMEN']

In [ ]:
# Dictionary to store the filtered DataFrames
filtered_datasets = {}

# Loop through unique values of 'Sector_Neta' and 'Canonical' to filter the dataset
for sector in unique_sector_neta:
    for canonical in unique_canonical:
        key = f"sector_{sector}_canonical_{canonical}"
        filtered_datasets[key] = df[(df['Sector_Neta'] == sector) & (df['Canonical'] == canonical)]

# Display the keys for the filtered datasets to provide an overview of the splits
list(filtered_datasets.keys())

In [38]:
zero_row_dict = {}
non_zero_row_dict = {}
for key in filtered_datasets:
    if filtered_datasets[key].shape[0] ==0:
        zero_row_dict[key] = filtered_datasets[key]
    else:
        non_zero_row_dict[key] = filtered_datasets[key]

In [41]:
for i in zero_row_dict:
    print(i)
    print(zero_row_dict[i].shape[0])

sector_22120000_canonical_PRESION_SALIDA_SECTOR
0
sector_22120000_canonical_VOLUMEN
0
sector_22121000_canonical_TOTALIZADOR
0
sector_22121000_canonical_PRESION_ENTRADA_SECTOR
0
sector_22121000_canonical_PRESION_SALIDA_SECTOR
0
sector_22121000_canonical_VOLUMEN
0
sector_22130000_canonical_VOLUMEN_DIARIO
0
sector_22130000_canonical_PRESION_SALIDA_SECTOR
0
sector_22130000_canonical_VOLUMEN
0
sector_22110000_canonical_PRESION_SALIDA_SECTOR
0
sector_22110000_canonical_VOLUMEN
0
sector_22131000_canonical_PRESION_SALIDA_SECTOR
0
sector_22131000_canonical_VOLUMEN
0
sector_22132100_canonical_PRESION_SALIDA_SECTOR
0
sector_22132100_canonical_VOLUMEN
0
sector_22122000_canonical_VOLUMEN
0
sector_22122100_canonical_TOTALIZADOR
0
sector_22122100_canonical_PRESION_ENTRADA_SECTOR
0
sector_22122100_canonical_VOLUMEN_DIARIO
0
sector_22122100_canonical_PRESION_SALIDA_SECTOR
0

In [ ]:
non_zero_row_dict

In [25]:
import os

In [26]:
#current directory
os.getcwd()

'c:\\Users\\lalit\\Desktop\\IE\\SEM II\\datathon'

In [30]:
# Directory to save the CSV files
output_directory_series = "data_series"

# Create the directory if it doesn't exist
if not os.path.exists(output_directory_series):
    os.makedirs(output_directory_series)

# Save the filtered datasets to CSV again
for key, data in filtered_datasets.items():
    # Retain only the specified columns
    data = data[['RowKey', 'INF_Value']]
    
    # Save to CSV
    filename = f"{key}.csv"
    filepath = output_directory_series + filename
    data.to_csv(filepath, index=False)

output_directory_series

'data_series'

In [ ]:
#run a for loop to find the name and shape of all files

In [35]:
os.listdir(output_directory_series)

['data_seriessector_22110000_canonical_CAUDAL.csv',
 'data_seriessector_22110000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22110000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22110000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22110000_canonical_VOLUMEN.csv',
 'data_seriessector_22110000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22120000_canonical_CAUDAL.csv',
 'data_seriessector_22120000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22120000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22120000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22120000_canonical_VOLUMEN.csv',
 'data_seriessector_22120000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22121000_canonical_CAUDAL.csv',
 'data_seriessector_22121000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22121000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22121000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22121000_canonical_VOLUMEN.csv',
 'data_seriessector_22121000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22122000_canonical_CAUDAL.csv',
 'data_seriessector_22122000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22122000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22122000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22122000_canonical_VOLUMEN.csv',
 'data_seriessector_22122000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22122100_canonical_CAUDAL.csv',
 'data_seriessector_22122100_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22122100_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22122100_canonical_TOTALIZADOR.csv',
 'data_seriessector_22122100_canonical_VOLUMEN.csv',
 'data_seriessector_22122100_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22130000_canonical_CAUDAL.csv',
 'data_seriessector_22130000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22130000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22130000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22130000_canonical_VOLUMEN.csv',
 'data_seriessector_22130000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22131000_canonical_CAUDAL.csv',
 'data_seriessector_22131000_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22131000_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22131000_canonical_TOTALIZADOR.csv',
 'data_seriessector_22131000_canonical_VOLUMEN.csv',
 'data_seriessector_22131000_canonical_VOLUMEN_DIARIO.csv',
 'data_seriessector_22132100_canonical_CAUDAL.csv',
 'data_seriessector_22132100_canonical_PRESION_ENTRADA_SECTOR.csv',
 'data_seriessector_22132100_canonical_PRESION_SALIDA_SECTOR.csv',
 'data_seriessector_22132100_canonical_TOTALIZADOR.csv',
 'data_seriessector_22132100_canonical_VOLUMEN.csv',
 'data_seriessector_22132100_canonical_VOLUMEN_DIARIO.csv',
 'series.ipynb']

In [43]:

# Save the filtered datasets to CSV again
for key, data in non_zero_row_dict.items():
    # Retain only the specified columns
    data = data[['RowKey', 'INF_Value']]
    
    # Save to CSV
    filename = f"{key}.csv"
    filepath = filename
    data.to_csv(filepath, index=False)

In [46]:
#convert keys to list
non_zero_row_dict_keys = list(non_zero_row_dict.keys())

In [47]:
non_zero_row_dict_keys

['sector_22120000_canonical_TOTALIZADOR',
 'sector_22120000_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22120000_canonical_VOLUMEN_DIARIO',
 'sector_22120000_canonical_CAUDAL',
 'sector_22121000_canonical_VOLUMEN_DIARIO',
 'sector_22121000_canonical_CAUDAL',
 'sector_22130000_canonical_TOTALIZADOR',
 'sector_22130000_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22130000_canonical_CAUDAL',
 'sector_22110000_canonical_TOTALIZADOR',
 'sector_22110000_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22110000_canonical_VOLUMEN_DIARIO',
 'sector_22110000_canonical_CAUDAL',
 'sector_22131000_canonical_TOTALIZADOR',
 'sector_22131000_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22131000_canonical_VOLUMEN_DIARIO',
 'sector_22131000_canonical_CAUDAL',
 'sector_22132100_canonical_TOTALIZADOR',
 'sector_22132100_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22132100_canonical_VOLUMEN_DIARIO',
 'sector_22132100_canonical_CAUDAL',
 'sector_22122000_canonical_TOTALIZADOR',
 'sector_22122000_canonical_PRESION_ENTRADA_SECTOR',
 'sector_22122000_canonical_VOLUMEN_DIARIO',
 'sector_22122000_canonical_CAUDAL',
 'sector_22122000_canonical_PRESION_SALIDA_SECTOR',
 'sector_22122100_canonical_CAUDAL',
 'sector_22122100_canonical_VOLUMEN']