In [35]:
import pandas as pd
clima = pd.read_csv('clima.csv')

In [36]:
clima.head()

,wdir,temp,maxt,visibility,wspd,datetimeStr,solarenergy,heatindex,cloudcover,mint,...,sealevelpressure,snow,dew,humidity,precipcover,wgust,conditions,windchill,info,locations
0,264.50,4.4,7.1,15.3,22.1,2021-01-01T00:00:00+01:00,7.4,NaN,55.3,2.1,...,1012.6,0.0,1.8,83.64,12.5,NaN,"Rain, Partially cloudy",-1.5,NaN,"39.2210171,-3.6185337"
1,291.04,2.1,6.9,19.6,18.5,2021-01-02T00:00:00+01:00,8.3,NaN,25.0,-1.3,...,1016.4,0.0,-3.3,70.25,0.0,NaN,Clear,-3.9,NaN,"39.2210171,-3.6185337"
2,252.50,2.0,8.1,20.0,13.0,2021-01-03T00:00:00+01:00,9.2,NaN,NaN,-2.9,...,1018.6,0.0,-4.4,63.87,0.0,NaN,Clear,-4.5,NaN,"39.2210171,-3.6185337"
3,255.58,1.2,3.8,14.6,18.4,2021-01-04T00:00:00+01:00,2.7,NaN,68.5,-1.2,...,1015.3,0.0,-0.1,90.94,0.0,NaN,Partially cloudy,-2.9,NaN,"39.2210171,-3.6185337"
4,138.75,-0.9,5.0,9.4,8.8,2021-01-05T00:00:00+01:00,7.6,NaN,61.1,-4.5,...,1014.7,0.0,-2.4,90.55,0.0,NaN,Partially cloudy,-5.4,NaN,"39.2210171,-3.6185337"

In [37]:
clima['locations'].unique()

array(['39.2210171,-3.6185337', '39.5473041962222,2.38945489891581',
       '38.4230642610591,-6.41439677433768'], dtype=object)

In [38]:

# Create a mapping dictionary based on the provided location coordinates and names
location_mapping = {
    '39.2210171,-3.6185337': 'Villarrubia',
    '39.5473041962222,2.38945489891581': 'Andratx-Palma',
    '38.4230642610591,-6.41439677433768': 'Zafra'
}

# Create the new column 'location_name' based on the mapping
clima['location_name'] = clima['locations'].map(location_mapping)

# Display the first few rows of the updated DataFrame
clima.head()

,wdir,temp,maxt,visibility,wspd,datetimeStr,solarenergy,heatindex,cloudcover,mint,...,snow,dew,humidity,precipcover,wgust,conditions,windchill,info,locations,location_name
0,264.50,4.4,7.1,15.3,22.1,2021-01-01T00:00:00+01:00,7.4,NaN,55.3,2.1,...,0.0,1.8,83.64,12.5,NaN,"Rain, Partially cloudy",-1.5,NaN,"39.2210171,-3.6185337",Villarrubia
1,291.04,2.1,6.9,19.6,18.5,2021-01-02T00:00:00+01:00,8.3,NaN,25.0,-1.3,...,0.0,-3.3,70.25,0.0,NaN,Clear,-3.9,NaN,"39.2210171,-3.6185337",Villarrubia
2,252.50,2.0,8.1,20.0,13.0,2021-01-03T00:00:00+01:00,9.2,NaN,NaN,-2.9,...,0.0,-4.4,63.87,0.0,NaN,Clear,-4.5,NaN,"39.2210171,-3.6185337",Villarrubia
3,255.58,1.2,3.8,14.6,18.4,2021-01-04T00:00:00+01:00,2.7,NaN,68.5,-1.2,...,0.0,-0.1,90.94,0.0,NaN,Partially cloudy,-2.9,NaN,"39.2210171,-3.6185337",Villarrubia
4,138.75,-0.9,5.0,9.4,8.8,2021-01-05T00:00:00+01:00,7.6,NaN,61.1,-4.5,...,0.0,-2.4,90.55,0.0,NaN,Partially cloudy,-5.4,NaN,"39.2210171,-3.6185337",Villarrubia

In [39]:
clima['location_name'].unique()

array(['Villarrubia', 'Andratx-Palma', 'Zafra'], dtype=object)

In [40]:
# Filter the DataFrame to include only rows where the location_name is 'Villarrubia'
clima_clean_df = clima[clima['location_name'] == 'Villarrubia']

# Display the first few rows of the new DataFrame
clima_clean_df.head()

,wdir,temp,maxt,visibility,wspd,datetimeStr,solarenergy,heatindex,cloudcover,mint,...,snow,dew,humidity,precipcover,wgust,conditions,windchill,info,locations,location_name
0,264.50,4.4,7.1,15.3,22.1,2021-01-01T00:00:00+01:00,7.4,NaN,55.3,2.1,...,0.0,1.8,83.64,12.5,NaN,"Rain, Partially cloudy",-1.5,NaN,"39.2210171,-3.6185337",Villarrubia
1,291.04,2.1,6.9,19.6,18.5,2021-01-02T00:00:00+01:00,8.3,NaN,25.0,-1.3,...,0.0,-3.3,70.25,0.0,NaN,Clear,-3.9,NaN,"39.2210171,-3.6185337",Villarrubia
2,252.50,2.0,8.1,20.0,13.0,2021-01-03T00:00:00+01:00,9.2,NaN,NaN,-2.9,...,0.0,-4.4,63.87,0.0,NaN,Clear,-4.5,NaN,"39.2210171,-3.6185337",Villarrubia
3,255.58,1.2,3.8,14.6,18.4,2021-01-04T00:00:00+01:00,2.7,NaN,68.5,-1.2,...,0.0,-0.1,90.94,0.0,NaN,Partially cloudy,-2.9,NaN,"39.2210171,-3.6185337",Villarrubia
4,138.75,-0.9,5.0,9.4,8.8,2021-01-05T00:00:00+01:00,7.6,NaN,61.1,-4.5,...,0.0,-2.4,90.55,0.0,NaN,Partially cloudy,-5.4,NaN,"39.2210171,-3.6185337",Villarrubia

In [41]:
#save
clima_clean_df.to_csv('clima_Villarubia.csv', index=False)

In [14]:
# Convert the 'datetimeStr' column to datetime format and then separate the date and time
clima_clean_df['date'] = pd.to_datetime(clima_clean_df['datetimeStr'], utc=True).dt.date
clima_clean_df['time'] = pd.to_datetime(clima_clean_df['datetimeStr'], utc=True).dt.time

# Display the first few rows of the updated DataFrame
clima_clean_df[['datetimeStr', 'date', 'time']].head()

C:\Users\lalit\AppData\Local\Temp\ipykernel_21388\3174635373.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clima_clean_df['date'] = pd.to_datetime(clima_clean_df['datetimeStr'], utc=True).dt.date
C:\Users\lalit\AppData\Local\Temp\ipykernel_21388\3174635373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clima_clean_df['time'] = pd.to_datetime(clima_clean_df['datetimeStr'], utc=True).dt.time

                 datetimeStr        date      time
0  2021-01-01T00:00:00+01:00  2020-12-31  23:00:00
1  2021-01-02T00:00:00+01:00  2021-01-01  23:00:00
2  2021-01-03T00:00:00+01:00  2021-01-02  23:00:00
3  2021-01-04T00:00:00+01:00  2021-01-03  23:00:00
4  2021-01-05T00:00:00+01:00  2021-01-04  23:00:00

In [15]:
# Adjust the 'date' column by adding one day
clima_clean_df['date'] = clima_clean_df['date'] + pd.Timedelta(days=1)

# Drop the 'time' column
clima_clean_df = clima_clean_df.drop(columns=['time'])

# Display the first few rows of the updated DataFrame
clima_clean_df[['datetimeStr', 'date']].head()

C:\Users\lalit\AppData\Local\Temp\ipykernel_21388\247479094.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clima_clean_df['date'] = clima_clean_df['date'] + pd.Timedelta(days=1)

                 datetimeStr        date
0  2021-01-01T00:00:00+01:00  2021-01-01
1  2021-01-02T00:00:00+01:00  2021-01-02
2  2021-01-03T00:00:00+01:00  2021-01-03
3  2021-01-04T00:00:00+01:00  2021-01-04
4  2021-01-05T00:00:00+01:00  2021-01-05

In [18]:
# Convert the string literals to datetime.date objects
start_date = pd.to_datetime('2021-08-01').date()
end_date = pd.to_datetime('2022-07-17').date()

# Filter the DataFrame based on the specified date range
filtered_clima_df = clima_clean_df[(clima_clean_df['date'] >= start_date) & (clima_clean_df['date'] <= end_date)]

# Display the first few rows of the filtered DataFrame
filtered_clima_df.head()

,wdir,temp,maxt,visibility,wspd,datetimeStr,solarenergy,heatindex,cloudcover,mint,...,dew,humidity,precipcover,wgust,conditions,windchill,info,locations,location_name,date
212,202.46,22.2,28.3,15.9,17.7,2021-08-01T00:00:00+02:00,22.9,26.9,27.1,13.2,...,5.7,38.07,0.0,31.7,Partially cloudy,NaN,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-01
213,247.13,24.0,30.3,14.8,10.6,2021-08-02T00:00:00+02:00,24.4,28.5,29.4,14.2,...,3.8,27.87,0.0,27.7,Partially cloudy,NaN,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-02
214,205.26,25.8,33.0,14.6,12.4,2021-08-03T00:00:00+02:00,24.7,30.9,33.7,15.3,...,7.7,35.15,0.0,NaN,Partially cloudy,NaN,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-03
215,264.83,27.3,33.0,14.8,16.2,2021-08-04T00:00:00+02:00,25.3,31.0,22.9,21.2,...,8.0,30.15,0.0,NaN,Clear,NaN,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-04
216,261.25,28.4,35.1,14.8,20.5,2021-08-05T00:00:00+02:00,25.3,32.5,0.0,19.6,...,5.5,25.73,0.0,NaN,Clear,NaN,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-05

In [21]:
filtered_clima_df['date'].value_counts().sum()

351

In [23]:
filtered_clima_df.shape

(351, 27)

In [24]:
filtered_clima_df.isna().sum()/len(filtered_clima_df)*100

wdir                  0.000000
temp                  0.000000
maxt                  0.000000
visibility            0.000000
wspd                  0.000000
datetimeStr           0.000000
solarenergy           0.000000
heatindex            66.381766
cloudcover           16.524217
mint                  0.000000
datetime              0.000000
precip                0.000000
solarradiation        0.000000
weathertype          41.595442
snowdepth            56.410256
sealevelpressure      0.000000
snow                 56.410256
dew                   0.000000
humidity              0.000000
precipcover           0.000000
wgust                75.498575
conditions            0.000000
windchill            54.415954
info                100.000000
locations             0.000000
location_name         0.000000
date                  0.000000
dtype: float64

In [25]:
filtered_clima_df['wgust'].unique()

array([ 31.7,  27.7,   nan,  48.2,  40.7,  33.5,  37.1,  38.9,  35.3,
        44.6,  29.5,  46.4,  50. , 108. ,  42.5,  53.6,  55.4,  66.6,
        72. ,  63. ,  25.9,  57.6])

In [27]:
filtered_clima_df = filtered_clima_df.drop(columns=['info'])

In [28]:
#save to csv
filtered_clima_df.to_csv('filtered_clima.csv', index=False)

In [29]:
# Function to aggregate weather types into broader categories
def aggregate_weathertype(weather_str):
    if pd.isnull(weather_str):
        return 'Unknown'
    if any(term in weather_str for term in ['Rain', 'Drizzle', 'Thunderstorm']):
        return 'Rainy'
    if any(term in weather_str for term in ['Mist', 'Fog']):
        return 'Misty'
    if any(term in weather_str for term in ['Sky Unchanged', 'Sky Coverage Decreasing', 'Clear']):
        return 'Clear'
    return 'Other'

# Apply the aggregation function to the 'weathertype' column
filtered_clima_df['aggregated_weathertype'] = filtered_clima_df['weathertype'].apply(aggregate_weathertype)

# Check the distribution of the new aggregated column
aggregated_distribution = filtered_clima_df['aggregated_weathertype'].value_counts()

aggregated_distribution

aggregated_weathertype
Unknown    146
Misty      105
Rainy       91
Clear        8
Other        1
Name: count, dtype: int64

In [34]:
filtered_clima_df

,wdir,temp,maxt,visibility,wspd,datetimeStr,solarenergy,heatindex,cloudcover,mint,...,wgust,conditions,windchill,locations,location_name,date,aggregated_weathertype,day,month,year
212,202.46,22.2,28.3,15.9,17.7,2021-08-01T00:00:00+02:00,22.9,26.9,27.1,13.2,...,31.7,Partially cloudy,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-01,Misty,1,8,2021
213,247.13,24.0,30.3,14.8,10.6,2021-08-02T00:00:00+02:00,24.4,28.5,29.4,14.2,...,27.7,Partially cloudy,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-02,Misty,2,8,2021
214,205.26,25.8,33.0,14.6,12.4,2021-08-03T00:00:00+02:00,24.7,30.9,33.7,15.3,...,NaN,Partially cloudy,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-03,Clear,3,8,2021
215,264.83,27.3,33.0,14.8,16.2,2021-08-04T00:00:00+02:00,25.3,31.0,22.9,21.2,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-04,Misty,4,8,2021
216,261.25,28.4,35.1,14.8,20.5,2021-08-05T00:00:00+02:00,25.3,32.5,0.0,19.6,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2021-08-05,Misty,5,8,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,161.46,31.3,39.9,14.9,9.4,2022-07-13T00:00:00+02:00,22.4,37.4,27.1,19.3,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2022-07-13,Unknown,13,7,2022
1289,181.63,32.6,40.0,14.7,9.4,2022-07-14T00:00:00+02:00,24.3,37.5,27.1,22.2,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2022-07-14,Unknown,14,7,2022
1290,135.92,31.6,39.6,14.5,16.0,2022-07-15T00:00:00+02:00,25.1,37.1,27.1,20.2,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2022-07-15,Unknown,15,7,2022
1291,107.71,32.0,39.0,15.6,16.7,2022-07-16T00:00:00+02:00,24.7,36.4,27.1,20.9,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2022-07-16,Unknown,16,7,2022
1292,94.63,31.6,39.2,15.9,17.3,2022-07-17T00:00:00+02:00,25.7,36.0,27.1,19.2,...,NaN,Clear,NaN,"39.2210171,-3.6185337",Villarrubia,2022-07-17,Unknown,17,7,2022

In [31]:
# Convert the 'date' column to datetime format
filtered_clima_df['date'] = pd.to_datetime(filtered_clima_df['date'])

# Extract day, month, and year and create separate columns
filtered_clima_df['day'] = filtered_clima_df['date'].dt.day
filtered_clima_df['month'] = filtered_clima_df['date'].dt.month
filtered_clima_df['year'] = filtered_clima_df['date'].dt.year

# Display the first few rows to verify the changes
filtered_clima_df[['date', 'day', 'month', 'year']].head()

          date  day  month  year
212 2021-08-01    1      8  2021
213 2021-08-02    2      8  2021
214 2021-08-03    3      8  2021
215 2021-08-04    4      8  2021
216 2021-08-05    5      8  2021

In [32]:
filtered_clima_df['location_name'].unique()

array(['Villarrubia'], dtype=object)

In [33]:
# Step 1: Group by 'location_name', 'day', and 'month' and calculate the mean for 'cloudcover'
cloudcover_filler = filtered_clima_df.groupby(['location_name', 'day', 'month'])['cloudcover'].transform('mean')

# Fill missing values in the 'cloudcover' column using the calculated filler
filtered_clima_df['cloudcover'].fillna(cloudcover_filler, inplace=True)

# Forward fill any remaining missing values
filtered_clima_df['cloudcover'].fillna(method='ffill', inplace=True)

# Check the number of missing values in 'cloudcover' after filling
missing_cloudcover = filtered_clima_df['cloudcover'].isnull().sum()

missing_cloudcover

0

In [ ]:
# Perform an inner merge based on the dates present in merged3_df
merged_with_clima_df = pd.merge(merged_df2, filtered_clima_df, left_on='Date', right_on='date', how='left')

# Display the first few rows of the merged dataframe
merged_df.head()